name = "tes"
main = "_workervl.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "tes.blondies.cfd"
custom_domain = true



[vars]
PROXYIP = "128.199.228.44"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_RESOLVER_URL = "https://dns.google.com/dns-query"
