name = "test"
main = "_workeori.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "my3.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "shopee.co.id.my3.freevpn.biz.id"
custom_domain = true

[vars]
PROXYIP = "103.75.188.126"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_NYA = "dns-adguard.com/dns-query"
