name = "my1"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "my1.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "shopee.co.id.my1.freevpn.biz.id"
custom_domain = true

[vars]
PROXYIP = "103.75.188.126"
PASSWORD = "bodongvpn"
