name = "test"
main = "_workervl.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "test.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "shopee.co.id.test.freevpn.biz.id"
custom_domain = true

[vars]
PROXYIP = "192.230.103.177"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_RESOLVER_URL = "https://dns.google.com/dns-query"
