name = "id1"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "id1.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "shopee.co.id.id1.freevpn.biz.id"
custom_domain = true

[vars]
PROXYIP = "35.219.50.99"
PASSWORD = "bodongvpn"
