name = "sg1" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "sg1.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "shopee.co.id.sg1.freevpn.biz.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa5"
PROXYIP = "128.199.228.44"
DNS_NYA = "dns.adguard.com/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
